name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Generated snake contribution grid" || echo "No changes to commit"
          git push
